# Generated by Django 5.1 on 2024-09-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('G', 'GeneralUser'), ('S', 'SuperUser')], default='G', max_length=1),
        ),
    ]
