# Generated by Django 5.1 on 2024-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_average_rating_product_dislike_and_more'),
        ('user', '0002_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_products',
            field=models.ManyToManyField(blank=True, related_name='disliked_by_users', to='product.product'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='product.product'),
        ),
        migrations.AddField(
            model_name='user',
            name='viewed_products',
            field=models.ManyToManyField(blank=True, related_name='viewed_by_users', to='product.product'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
