# Generated by Django 5.1 on 2024-10-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_disliked_products_user_liked_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disliked_products',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_products',
        ),
        migrations.RemoveField(
            model_name='user',
            name='viewed_products',
        ),
    ]
