export const RouteConstant = {
    Login: 'login',
    Registration: 'register',
    ForgotPassword: 'forgotPassword',
    Account: 'account',
    Home: 'home',
    Product: 'product',
    Cart: 'cart',
    Summary: 'summary',
    Profile: 'profile',
    AddProduct: 'addProduct',
    UpdateProduct: 'updateProduct',
    Notification: 'notification',
    ProductStatus: 'status',
}