/*
-- Query: SELECT * FROM e_commerce.product_product
LIMIT 0, 1000

-- Date: 2024-09-10 08:21
*/
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (1,'Paddie','Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.','lorem vitae',654.40,1,32,'15678-78-1.jpg',1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (2,'Kiri','Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.','volutpat',654.40,2,18,'dell_2BePqqQ.jpeg',1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (3,'Brigit','Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.','fusce posuere',176.20,1,98,'item_XL_115702825_b52c966a6e8c5.jpg',2);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (4,'Dukey','Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.','vestibulum',555.60,1,81,NULL,1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (5,'Mufinella','Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.','suscipit a',781.80,2,50,NULL,2);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (6,'Kristine','Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.','sem',106.60,2,19,NULL,1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (7,'Welby','Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.','ligula',852.90,1,5,NULL,1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (8,'Lock','Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.','tristique',396.20,1,7,NULL,1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (9,'Edwina','Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.','duis consequat',418.20,1,74,NULL,2);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (10,'Reinald','Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.','curae',703.50,1,44,NULL,1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (11,'Harbert','Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.','elementum nullam',766.80,2,74,NULL,1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (12,'Hadrian','Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.','justo',404.60,1,56,NULL,2);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (13,'Hedvig','Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.','sapien',344.80,1,55,NULL,2);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (14,'Patric','Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.','quis orci',447.70,1,91,NULL,1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (15,'Grier','Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.','habitasse',875.80,2,27,NULL,1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (16,'Merrick','Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.','quam',609.30,1,30,NULL,2);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (17,'Guy','Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.','bibendum',436.40,1,70,NULL,1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (18,'Kristoforo','Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.','quam suspendisse',185.80,2,44,'http://dummyimage.com/173x100.png/5fa2dd/ffffff',2);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (19,'Madelina','Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','porttitor lorem',218.60,1,94,NULL,1);
INSERT INTO `` (`id`,`name`,`description`,`model`,`price`,`BID_id`,`stock_items`,`base_view`,`CategoryID_id`) VALUES (20,'Udell','In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.','mi integer',952.50,2,18,NULL,2);
