# Generated by Django 5.0.7 on 2024-10-03 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_alter_category_image'),
        ('user', '0002_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(verbose_name='Search keyword')),
                ('UID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user ID')),
            ],
        ),
        migrations.CreateModel(
            name='VisitActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_vist', models.IntegerField(default=1)),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product ID')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user ID')),
            ],
        ),
    ]
