# Generated by Django 5.1 on 2024-10-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productcomment_uid'),
        ('recomendation', '0001_initial'),
        ('user', '0004_remove_user_disliked_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitActivity',
            new_name='ViewActivity',
        ),
        migrations.CreateModel(
            name='DislikedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked', models.IntegerField(default=0)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product ID')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user ID')),
            ],
        ),
        migrations.CreateModel(
            name='LikedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.IntegerField(default=1)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product ID')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user ID')),
            ],
        ),
    ]
