# Generated by Django 5.1 on 2024-10-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation', '0002_rename_visitactivity_viewactivity_dislikedproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedproduct',
            old_name='liked',
            new_name='preference',
        ),
        migrations.DeleteModel(
            name='DislikedProduct',
        ),
    ]
