# Generated by Django 5.1 on 2024-09-09 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of Category')),
                ('image', models.ImageField(upload_to='category/', verbose_name='Image')),
                ('catParent', models.ForeignKey(blank=True, limit_choices_to={'catParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of Brand')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('model', models.CharField(max_length=30, verbose_name='Product Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Product Price')),
                ('stock_items', models.IntegerField(verbose_name='Product Items in Stock')),
                ('base_view', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Product  Image')),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand', verbose_name='Brand ID')),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Product Comment')),
                ('review', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Product Stars Review')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product ID')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='User ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_view', models.ImageField(upload_to='', verbose_name='Product Front Image')),
                ('top_view', models.ImageField(upload_to='', verbose_name='Product Top Image')),
                ('side_view', models.ImageField(upload_to='', verbose_name='Product Side Image')),
                ('inner_view', models.ImageField(upload_to='', verbose_name='Product Inner Image')),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product ID')),
            ],
        ),
    ]
