# Generated by Django 5.1 on 2024-09-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
