# Generated by Django 5.1 on 2024-10-10 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='disLike',
            field=models.IntegerField(default=0, verbose_name='Dislike by User'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_puchases',
            field=models.IntegerField(default=0, verbose_name='Product Items total puchese'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_view',
            field=models.IntegerField(default=0, verbose_name='Product Items total views'),
        ),
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Like by User'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
    ]
