# Generated by Django 5.1 on 2024-10-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_average_rating_product_dislike_and_more'),
        ('user', '0004_remove_user_disliked_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='User ID'),
        ),
    ]
