# Generated by Django 5.1 on 2024-11-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cluster',
            field=models.IntegerField(default=-1, verbose_name='Cluster ID'),
        ),
    ]
